name = "voluntai"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "service-finder-db"
database_id = "a544f65a-afd0-4548-83de-7ae12310123f"
migrations_dir = "src/lib/db/migrations"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "voluntai-images"

[[kv_namespaces]]
binding = "CACHE"
id = "d97b785ac5834183b16c7f8d8cb9efdb"

[[kv_namespaces]]
binding = "SESSION"
id = "227707d39f1943938b2636ac52ca6eff"

[ai]
binding = "AI"

[vars]
ENVIRONMENT = "production"
APP_BASE_URL = "https://voluntai.com"
