// Cloudflare Worker bindings interface.
// The actual worker entry is generated by @astrojs/cloudflare in dist/_worker.js.
// Import this Env type wherever you need typed access to bindings.

export interface Env {
  DB: D1Database;
  IMAGES: R2Bucket;
  CACHE: KVNamespace;
  AI: Ai;
  ENVIRONMENT: string;
  APP_BASE_URL: string;
}
